### ISSUE TITLE
Ask about the clinical part

### ISSUE THREAD

**Issue by pipaber** [ETH-NEXUS/scAmpi_single_cell_RNA#12]
Hi scAmpi team,

I have doubts about the clinical part. I tried to run it on prostate cancer datasets (PRJNA768795 bioproject) from the ENA database but it seems that i´m doing something wrong.

Here is the log file:

`2022-12-12 23:08:30 [runtime] (failed)          ID.prostate.SC_RNA_COUNTER_CS.SC_MULTI_CORE.MULTI_CHEMISTRY_DETECTOR._
GEM_WELL_CHEMISTRY_DETECTOR.DETECT_COUNT_CHEMISTRY

[error] Pipestance failed. Error log at:
prostate/SC_RNA_COUNTER_CS/SC_MULTI_CORE/MULTI_CHEMISTRY_DETECTOR/_GEM_WELL_CHEMISTRY_DETECTOR/DETECT_COUNT_CHEMISTRY/
fork0/chnk0-u665197b3cc/_errors

Log message:
Unable to distinguish between [SC5P-PE, SC3Pv2] chemistries based on the R2 read mapping for Sample prostate in "/home
/username/scAmpi_single_cell_RNA/workflow/fastqs".
Total Reads          = 100000
Mapped reads         = 1
Sense reads          = 0
Antisense reads      = 0

In order to distinguish between the 3' vs 5' assay configuration the following conditions need to be satisfied:
- A minimum of 1000 confidently mapped reads
- A minimum of 5.0% of the total reads considered needs to be confidently mapped
- The number of sense reads need to be at least 2x compared to the antisense reads or vice versa

Please validate the inputs and/or specify the chemistry via the --chemistry argument.`

Also, I wanna ask: there's are a testdataset for the clinical part of the pipeline? Because when I run the clinical script on the test dataset used for the basic script, I dont see the drugs plot. Or how should I specify the datasets from databases like NCBI or ENA?

Thanks in advance,

Piero Palacios.

**Comment by aricht** [comment]
Hi Piero,

to answer your last question first, unfortunately we do not have test data for the clinical part. Since we are working with clinical data we cannot use our own samples, and we did not find any data set that was suitable for this purpose.

The error you describe comes from the Cellranger software. The default is that Cellranger detects when running which chemistry was used in the experiment, for details see [How does Cell Ranger auto-detect chemistry?](https://kb.10xgenomics.com/hc/en-us/articles/115003764132-How-does-Cell-Ranger-auto-detect-chemistry-).
In your case, it seems that only one of the sampled 100,000 reads could be mapped to the reference, and therefore Cellranger cannot infer which of the protocols was used to prepare the sample.

I advise you check if the Cellranger reference and the data you use are somehow not compatible?
Also, we will make it possible to specify the chemistry manually with the `--chemistry` parameter via a "various_params" section in the Cellranger rule that can be adapted in the config file.

Best,
Anne

**Comment by aricht** [comment]
Hi,
as of #15 you can now specify the Cellranger chemistry manually with the `--chemistry` parameter in the `various_params` section that can be adapted in the config file.
I hope this is helpful, I will close the issue.
Anne
