### ISSUE TITLE
Installation of workflows only

### ISSUE THREAD

**Issue by kadupena25** [ETH-NEXUS/scAmpi_single_cell_RNA#13]
Hi, 
I am trying to install Scampi on Ubuntu . I have installed anaconda and mamba and snakemake. 
Also have installed cellranger and STAR.
But when I try to install with this command:
snakemake --use-conda --conda-create-envs-only --conda-prefix /my/directory/for/conda/envs/ -s workflow/snakefile_basic.smk --configfile config/config.yaml
It returns this error:
Building DAG of jobs...
MissingInputException in rule cellranger_count in file /home/carlos/Downloads/scAmpi_single_cell_RNA-master/workflow/rules/scAmpi_basic_rules.smk, line 2:
Missing input files for rule cellranger_count:
    output: results/cellranger_run/SAMPLE-1_scR.features.tsv, results/cellranger_run/SAMPLE-1_scR.matrix.mtx, results/cellranger_run/SAMPLE-1_scR.barcodes.tsv
    wildcards: sample=SAMPLE-1_scR
    affected files:
        refdata-gex-GRCh38-2020-A
        /path/to/fastqs
Any advice?

**Comment by aricht** [comment]
Hi,
the problem seems to be that Snakemake cannot compile the dry run that is needed to specify the software that needs to be installed.

For all files defined as `input` in the rules, Snakemake checks if they exist or can be build with another rule. The input for the very first rule `cellranger_count` cannot be build with another rule, and therefore needs to exist.

You need to make sure that the two entries in `config/config.yaml`
- [inputOutput][input_fastqs]    
- [resources][reference_transcriptome]

exist, either by pointing to your actual cellranger reference directory and input files, or by pointing to a existing dummy file. With this the dry run should compile and the software be installed.
Best,
Anne
